# Generated by Django 5.0.1 on 2024-01-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompressedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='images/')),
                ('compressed_image', models.ImageField(blank=True, null=True, upload_to='compressed_images/')),
            ],
        ),
    ]
