# Generated by Django 5.0.1 on 2024-01-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
